"""
build_safe_pool.py — фильтр упражнений под клиента из PostgreSQL.

Читает каталог через db.queries, применяет condition-specific blacklists,
возвращает safe pool для последующей передачи в Opus-промпт генератора плана.

НИКОГДА не генерирует план сам — только готовит список безопасных упражнений.
План создаёт Opus.

Использование:
    python build_safe_pool.py --conditions lumbar_hernia
    python build_safe_pool.py --conditions "hypertension_grade_3,knee_OA_grade_1" --output safe_pool.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
sys.stdout.reconfigure(encoding="utf-8")

from db.queries import load_all_exercises, is_db_available


# ======================================================================
# BLACKLISTS — вручную курированные id под конкретные ограничения
# ======================================================================

# Упражнения, которые мы всегда исключаем из autogenerated планов
# (элитные гимнастические, акробатика, челлендж-движения)
GLOBAL_BLACKLIST: set[str] = set()

# Ключевые слова → exerciseId с такими паттернами исключаются
# (если условие у клиента)
CONDITION_FORBIDDEN_KEYWORDS: dict[str, list[str]] = {
    "lumbar_hernia": [
        # Осевая нагрузка на позвоночник
        "barbell squat", "barbell deadlift", "barbell bent over row",
        "good morning", "standing barbell press", "military press",
        # Сгибание под нагрузкой
        "roman chair", "seated good morning",
        # Ротация под нагрузкой
        "russian twist", "barbell twist", "wood chop", "woodchop",
    ],
    "knee_OA": [
        "deep squat", "jumping squat", "pistol squat",
        "plyometric", "box jump", "depth jump",
        "full squat",
    ],
    "hypertension_grade_3": [
        "inverted", "handstand", "headstand",
        "valsalva", "1rm",
    ],
    "shoulder_impingement": [
        "behind the neck", "upright row",
        "lateral raise above shoulder",
    ],
}


def filter_by_condition(catalog: dict, conditions: list[str]) -> tuple[dict, dict]:
    """Отфильтровать каталог, исключив forbidden по каждому условию.

    Возвращает (safe_pool_dict, excluded_by_condition_dict).
    """
    excluded_ids = set(GLOBAL_BLACKLIST)
    excluded_by = {"__global__": list(GLOBAL_BLACKLIST & set(catalog.keys()))}

    for cond in conditions:
        keywords = CONDITION_FORBIDDEN_KEYWORDS.get(cond, [])
        if not keywords:
            continue
        matched = []
        for eid, ex in catalog.items():
            name = ex.get("nameEn", "").lower()
            for kw in keywords:
                if kw.lower() in name:
                    excluded_ids.add(eid)
                    matched.append(eid)
                    break
        excluded_by[cond] = matched

    safe_pool = {
        eid: ex for eid, ex in catalog.items()
        if eid not in excluded_ids and ex.get("hasAnimation", True)
    }
    return safe_pool, excluded_by


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--conditions", default="", help="Comma-separated condition keys (lumbar_hernia, knee_OA_grade_1, etc.)")
    ap.add_argument("--output", default=None, help="Output JSON path (default: safe_pool_<hash>.json)")
    args = ap.parse_args()

    if not is_db_available():
        print("ERROR: PostgreSQL недоступен. Запусти: docker compose up -d", file=sys.stderr)
        sys.exit(1)

    conditions = [c.strip() for c in args.conditions.split(",") if c.strip()]
    catalog = load_all_exercises()
    safe_pool, excluded_by = filter_by_condition(catalog, conditions)

    out = {
        "meta": {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "conditions": conditions,
            "total_in": len(catalog),
            "total_out": len(safe_pool),
            "excluded_by": {k: len(v) for k, v in excluded_by.items()},
        },
        "exercises": list(safe_pool.values()),
    }

    out_path = args.output or f"safe_pool_{hashlib.md5(args.conditions.encode()).hexdigest()[:8]}.json"
    Path(out_path).write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"Safe pool: {out_path}")
    print(f"  Входной каталог: {len(catalog)}")
    print(f"  Safe pool:       {len(safe_pool)}")
    print(f"  Условия:         {conditions}")
    for cond, ids in excluded_by.items():
        print(f"    исключено ({cond}): {len(ids)}")


if __name__ == "__main__":
    main()
